title: African Mammels Alimentation
author: Marian Winston
email: marian.jitaru3@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  Orangos eat mangos but lions eat orangos (at least I think).
  Aliens enjoy the view from their UFO and eat space jelly worms.

# social links
twitter_username: your-twitter-handle
github_username:  MarianWinston

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
